<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <SiLlvmBuild Condition="'$(SI_LLVM_BUILD)' != ''">$(SI_LLVM_BUILD)</SiLlvmBuild>
    <SiLlvmBuild Condition="'$(SiLlvmBuild)' == '' and '$(DefaultPlatformToolset)' == 'ClangCL'">true</SiLlvmBuild>
    <SiLlvmBuild Condition="'$(SiLlvmBuild)' == ''">false</SiLlvmBuild>
    <SiLlvmLto Condition="'$(SI_LLVM_LTO)' != ''">$(SI_LLVM_LTO)</SiLlvmLto>
    <SiLlvmLto Condition="'$(SiLlvmLto)' == '' and '$(SiLlvmBuild)' == 'true' and '$(SI_UNSAFE_BUILD)' == 'true'">true</SiLlvmLto>
    <SiLlvmLto Condition="'$(SiLlvmLto)' == ''">false</SiLlvmLto>
    <SiMsvcNoDateOption Condition="'$(SiLlvmBuild)' != 'true'">/d1nodatetime</SiMsvcNoDateOption>
    <SiMsvcImportNoRegistryOption Condition="'$(SiLlvmBuild)' != 'true'">/d1import_no_registry</SiMsvcImportNoRegistryOption>
    <SiMsvcJumpTableOption Condition="'$(SiLlvmBuild)' != 'true'">/jumptablerdata</SiMsvcJumpTableOption>
    <SiMsvcGuardXfgCompileOption Condition="'$(SiLlvmBuild)' != 'true'">/guard:xfg</SiMsvcGuardXfgCompileOption>
    <SiMsvcGuardXfgLinkOption Condition="'$(SiLlvmBuild)' != 'true'">/GUARD:XFG</SiMsvcGuardXfgLinkOption>
    <SiMsvcLtcgLinkOption Condition="'$(SiLlvmBuild)' != 'true'">/LTCG</SiMsvcLtcgLinkOption>
    <SiMsvcPrivateLinkOptions Condition="'$(SiLlvmBuild)' != 'true'">/NOOPTIDATA /NOVCFEATURE /NOCOFFGRPINFO /BASERELOCCLUSTERING</SiMsvcPrivateLinkOptions>
    <SiMsvcTrimFileOption Condition="'$(SiLlvmBuild)' != 'true'">/d1trimfile:"$(MSBuildThisFileDirectory)\"</SiMsvcTrimFileOption>
    <SiLlvmCompileOptions Condition="'$(SiLlvmBuild)' == 'true'">/clang:-Wno-unused-command-line-argument /clang:-Wno-c23-extensions /clang:-Wno-unknown-pragmas /clang:-Wno-pragma-pack /clang:-Wno-pointer-sign /clang:-Wno-incompatible-pointer-types /clang:-Wno-microsoft-enum-forward-reference /clang:-Wno-parentheses /clang:-Wno-unused-variable /clang:-Wno-unused-local-typedef /clang:-Wno-reorder-ctor</SiLlvmCompileOptions>
    <SiLlvmCompileOptions Condition="'$(SiLlvmBuild)' == 'true' and '$(SiLlvmLto)' == 'true'">$(SiLlvmCompileOptions) /clang:-flto=full /clang:-ffunction-sections /clang:-fdata-sections</SiLlvmCompileOptions>
    <SiLlvmCompileOptions Condition="'$(SiLlvmBuild)' == 'true' and '$(SI_LLVM_NATIVE)' == 'true'">$(SiLlvmCompileOptions) /clang:-march=native</SiLlvmCompileOptions>
  </PropertyGroup>

  <!-- Global -->
  <ItemDefinitionGroup>
      <ClCompile>
          <TreatWarningAsError Condition="'$(SiLlvmBuild)' == 'true'">false</TreatWarningAsError>
          <TreatWarningAsError Condition="'$(SiLlvmBuild)' != 'true'">true</TreatWarningAsError>
          <WarningLevel>Level3</WarningLevel>
          <SDLCheck>true</SDLCheck>
          <MinimalRebuild>false</MinimalRebuild>
          <MultiProcessorCompilation>true</MultiProcessorCompilation>
          <LanguageStandard>stdcpplatest</LanguageStandard>
          <LanguageStandard_C Condition="'$(SiLlvmBuild)' != 'true'">stdclatest</LanguageStandard_C>
          <StringPooling>true</StringPooling>
          <SupportJustMyCode>false</SupportJustMyCode>
          <UseFullPaths>false</UseFullPaths>
          <UseStandardPreprocessor>true</UseStandardPreprocessor>
          <UseUnicodeForAssemblerListing>true</UseUnicodeForAssemblerListing>
          <ConformanceMode>true</ConformanceMode>
          <EnforceTypeConversionRules>true</EnforceTypeConversionRules>
          <WindowsTargetPlatformVersion>$(LatestTargetPlatformVersion)</WindowsTargetPlatformVersion>
      </ClCompile>
      <Link>
          <GenerateDebugInformation>true</GenerateDebugInformation>
          <SubSystem>Windows</SubSystem>
          <LargeAddressAware>true</LargeAddressAware>
      </Link>
      <Lib>
          <TreatLibWarningAsErrors Condition="'$(SiLlvmBuild)' == 'true'">false</TreatLibWarningAsErrors>
          <TreatLibWarningAsErrors Condition="'$(SiLlvmBuild)' != 'true'">true</TreatLibWarningAsErrors>
          <UseUnicodeResponseFiles>true</UseUnicodeResponseFiles>
          <LinkTimeCodeGeneration Condition="'$(SiLlvmBuild)' != 'true' or '$(SiLlvmLto)' == 'true'">true</LinkTimeCodeGeneration>
      </Lib>
      <ResourceCompile>
          <Culture>0x0009</Culture>
          <AdditionalOptions>/c 65001 %(AdditionalOptions)</AdditionalOptions>
          <PreprocessorDefinitions>%(PreprocessorDefinitions);$(ExternalPreprocessorOptions)</PreprocessorDefinitions>
      </ResourceCompile>
  </ItemDefinitionGroup>

  <!-- WPP Trace (optional, disabled by default)
       - Conditional based on presence of necessary WDK parts.
       - Set SI_WITH_WPP to enable WPP trace compile.
  -->
  <PropertyGroup>
    <SiNoWpp Condition="'$(SI_WITH_WPP)'==''">true</SiNoWpp>
  </PropertyGroup>
  <Target Name="SiRunWpp"
          BeforeTargets="BeforeClCompile"
          Condition="'$(SiNoWpp)'!='true' and Exists('$(WindowsSdkDir)\bin\$(TargetPlatformVersion)\WppConfig\Rev1\')"
          Inputs="@(ClInclude);@(ClCompile)"
          Outputs="@(ClInclude->'$(IntDir)tmh\%(Filename).tmh');@(ClCompile->'$(IntDir)tmh\%(Filename).tmh')">
      <MakeDir Directories="$(IntDir)tmh" Condition="!Exists('$(IntDir)tmh')" />
      <PropertyGroup>
          <TraceWppCmd>tracewpp.exe</TraceWppCmd>
          <TraceWppCmd>$(TraceWppCmd) -um</TraceWppCmd>
          <TraceWppCmd>$(TraceWppCmd) -ext:.c.cpp.h.hpp</TraceWppCmd>
          <TraceWppCmd>$(TraceWppCmd) -preserveext:.c.cpp.h.hpp</TraceWppCmd>
          <TraceWppCmd>$(TraceWppCmd) -I"$(WindowsSdkDir)bin\$(TargetPlatformVersion)\WppConfig\Rev1"</TraceWppCmd>
          <TraceWppCmd>$(TraceWppCmd) -odir:"$(IntDir)tmh"</TraceWppCmd>
          <TraceWppCmd>$(TraceWppCmd) -scan:"$(SystemInformerRoot)phlib\include\trace.h"</TraceWppCmd>
      </PropertyGroup>
      <Exec Command="$(TraceWppCmd) @(ClInclude->'&quot;%(FullPath)&quot;', ' ') @(ClCompile->'&quot;%(FullPath)&quot;', ' ')"/>
  </Target>
  <ItemDefinitionGroup Condition="'$(SiNoWpp)'!='true' and Exists('$(WindowsSdkDir)\bin\$(TargetPlatformVersion)\WppConfig\Rev1\')">
      <ClCompile>
          <AdditionalIncludeDirectories>%(AdditionalIncludeDirectories);$(IntDir)tmh\</AdditionalIncludeDirectories>
          <PreprocessorDefinitions>TMH_FILE=%(FileName)%(Extension).tmh;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(SiNoWpp)'=='true' or !Exists('$(WindowsSdkDir)\bin\$(TargetPlatformVersion)\WppConfig\Rev1\')">
      <ClCompile>
          <PreprocessorDefinitions>SI_NO_WPP;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      </ClCompile>
  </ItemDefinitionGroup>

  <!-- Debug Builds -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <CharacterSet>Unicode</CharacterSet>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>$(DefaultPlatformToolset)</PlatformToolset>
    <SpectreMitigation>false</SpectreMitigation>
    <LinkIncremental>true</LinkIncremental>
    <WholeProgramOptimization>false</WholeProgramOptimization>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
    <CharacterSet>Unicode</CharacterSet>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>$(DefaultPlatformToolset)</PlatformToolset>
    <SpectreMitigation>false</SpectreMitigation>
    <LinkIncremental>true</LinkIncremental>
    <WholeProgramOptimization>false</WholeProgramOptimization>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'" Label="Configuration">
    <CharacterSet>Unicode</CharacterSet>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>$(DefaultPlatformToolset)</PlatformToolset>
    <SpectreMitigation>false</SpectreMitigation>
    <LinkIncremental>true</LinkIncremental>
    <WholeProgramOptimization>false</WholeProgramOptimization>
  </PropertyGroup>
  <!-- Release Builds -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="Configuration">
    <CharacterSet>Unicode</CharacterSet>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>$(DefaultPlatformToolset)</PlatformToolset>
    <SpectreMitigation Condition="'$(SI_UNSAFE_BUILD)'=='true'">false</SpectreMitigation>
    <SpectreMitigation Condition="'$(SI_UNSAFE_BUILD)'!='true'">Spectre</SpectreMitigation>
    <LinkIncremental>false</LinkIncremental>
    <WholeProgramOptimization Condition="'$(SiLlvmBuild)' == 'true' and '$(SiLlvmLto)' != 'true'">false</WholeProgramOptimization>
    <WholeProgramOptimization Condition="'$(SiLlvmBuild)' != 'true' or '$(SiLlvmLto)' == 'true'">true</WholeProgramOptimization>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <CharacterSet>Unicode</CharacterSet>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>$(DefaultPlatformToolset)</PlatformToolset>
    <SpectreMitigation Condition="'$(SI_UNSAFE_BUILD)'=='true'">false</SpectreMitigation>
    <SpectreMitigation Condition="'$(SI_UNSAFE_BUILD)'!='true'">Spectre</SpectreMitigation>
    <LinkIncremental>false</LinkIncremental>
    <WholeProgramOptimization Condition="'$(SiLlvmBuild)' == 'true' and '$(SiLlvmLto)' != 'true'">false</WholeProgramOptimization>
    <WholeProgramOptimization Condition="'$(SiLlvmBuild)' != 'true' or '$(SiLlvmLto)' == 'true'">true</WholeProgramOptimization>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'" Label="Configuration">
    <CharacterSet>Unicode</CharacterSet>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>$(DefaultPlatformToolset)</PlatformToolset>
    <SpectreMitigation Condition="'$(SI_UNSAFE_BUILD)'=='true'">false</SpectreMitigation>
    <SpectreMitigation Condition="'$(SI_UNSAFE_BUILD)'!='true'">Spectre</SpectreMitigation>
    <LinkIncremental>false</LinkIncremental>
    <WholeProgramOptimization Condition="'$(SiLlvmBuild)' == 'true' and '$(SiLlvmLto)' != 'true'">false</WholeProgramOptimization>
    <WholeProgramOptimization Condition="'$(SiLlvmBuild)' != 'true' or '$(SiLlvmLto)' == 'true'">true</WholeProgramOptimization>
  </PropertyGroup>

  <!-- Debug|Win32 Builds -->
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
      <ClCompile>
          <AdditionalOptions>/utf-8 $(SiMsvcNoDateOption) %(AdditionalOptions) $(SiLlvmCompileOptions) $(ExternalAdditionalOptions)</AdditionalOptions>
          <PreprocessorDefinitions>WIN32;DEBUG;_DEBUG;_WINDOWS;_USRDLL;ENABLE_RESTRICTED;_DBG_MEMCPY_INLINE_;CONST_VTABLE;%(PreprocessorDefinitions);$(ExternalPreprocessorOptions)</PreprocessorDefinitions>
          <DebugInformationFormat>EditAndContinue</DebugInformationFormat>
          <EnableEnhancedInstructionSet>$(ExternalSimdOptions)</EnableEnhancedInstructionSet>
          <Optimization>Disabled</Optimization>
          <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>
          <CallingConvention>StdCall</CallingConvention>
          <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
          <FloatingPointModel>Precise</FloatingPointModel>
          <FunctionLevelLinking>true</FunctionLevelLinking>
          <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
          <WholeProgramOptimization>false</WholeProgramOptimization>
          <IntrinsicFunctions>true</IntrinsicFunctions>
      </ClCompile>
      <Link>
          <AdditionalOptions>/BREPRO /DEBUGTYPE:CV,PDATA /DEPENDENTLOADFLAG:0x800 /FILEALIGN:0x1000 /NOOPTIDATA /BASERELOCCLUSTERING /NATVIS:$(MSBuildThisFileDirectory)\SystemInformer.natvis %(AdditionalOptions) $(ExternalLinkerOptions)</AdditionalOptions>
          <AdditionalDependencies>invalidcontinue.obj;noarg.obj;noenv.obj;nothrownew.obj;%(AdditionalDependencies)</AdditionalDependencies>
          <MinimumRequiredVersion>6.01</MinimumRequiredVersion>
          <TargetMachine>MachineX86</TargetMachine>
          <FullProgramDatabaseFile>true</FullProgramDatabaseFile>
          <GenerateDebugInformation>true</GenerateDebugInformation>
          <UseUnicodeResponseFiles>true</UseUnicodeResponseFiles>
          <LinkTimeCodeGeneration>Default</LinkTimeCodeGeneration>
      </Link>
  </ItemDefinitionGroup>

  <!-- Debug|x64 Builds -->
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
      <ClCompile>
          <AdditionalOptions>/utf-8 $(SiMsvcNoDateOption) $(SiMsvcImportNoRegistryOption) $(SiMsvcJumpTableOption) %(AdditionalOptions) $(SiLlvmCompileOptions) $(ExternalAdditionalOptions)</AdditionalOptions>
          <PreprocessorDefinitions>WIN64;DEBUG;_DEBUG;_WINDOWS;_USRDLL;ENABLE_RESTRICTED;_DBG_MEMCPY_INLINE_;CONST_VTABLE;%(PreprocessorDefinitions);$(ExternalPreprocessorOptions)</PreprocessorDefinitions>
          <DebugInformationFormat>EditAndContinue</DebugInformationFormat>
          <EnableEnhancedInstructionSet>$(ExternalSimdOptions)</EnableEnhancedInstructionSet>
          <Optimization>Disabled</Optimization>
          <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>
          <CallingConvention>StdCall</CallingConvention>
          <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
          <FloatingPointModel>Precise</FloatingPointModel>
          <FunctionLevelLinking>true</FunctionLevelLinking>
          <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
          <WholeProgramOptimization>false</WholeProgramOptimization>
          <IntrinsicFunctions>true</IntrinsicFunctions>
      </ClCompile>
      <Link>
          <AdditionalOptions>/BREPRO /DEBUGTYPE:CV,PDATA /DEPENDENTLOADFLAG:0x800 /FILEALIGN:0x1000 /NOOPTIDATA /BASERELOCCLUSTERING /NATVIS:$(MSBuildThisFileDirectory)\SystemInformer.natvis %(AdditionalOptions) $(ExternalLinkerOptions)</AdditionalOptions>
          <AdditionalDependencies>invalidcontinue.obj;noarg.obj;noenv.obj;nothrownew.obj;%(AdditionalDependencies)</AdditionalDependencies>
          <MinimumRequiredVersion>6.01</MinimumRequiredVersion>
          <TargetMachine>MachineX64</TargetMachine>
          <FullProgramDatabaseFile>true</FullProgramDatabaseFile>
          <GenerateDebugInformation>true</GenerateDebugInformation>
          <UseUnicodeResponseFiles>true</UseUnicodeResponseFiles>
          <LinkTimeCodeGeneration>Default</LinkTimeCodeGeneration>
      </Link>
  </ItemDefinitionGroup>

  <!-- Debug|ARM64 Builds -->
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
      <ClCompile>
          <AdditionalOptions>/utf-8 $(SiMsvcNoDateOption) $(SiMsvcImportNoRegistryOption) %(AdditionalOptions) $(SiLlvmCompileOptions) $(ExternalAdditionalOptions)</AdditionalOptions>
          <PreprocessorDefinitions>WIN64;DEBUG;_DEBUG;_WINDOWS;_USRDLL;ENABLE_RESTRICTED;_DBG_MEMCPY_INLINE_;CONST_VTABLE;%(PreprocessorDefinitions);$(ExternalPreprocessorOptions)</PreprocessorDefinitions>
          <DebugInformationFormat>EditAndContinue</DebugInformationFormat>
          <EnableEnhancedInstructionSet>$(ExternalSimdOptions)</EnableEnhancedInstructionSet>
          <Optimization>Disabled</Optimization>
          <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>
          <CallingConvention>StdCall</CallingConvention>
          <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
          <FloatingPointModel>Precise</FloatingPointModel>
          <FunctionLevelLinking>true</FunctionLevelLinking>
          <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
          <WholeProgramOptimization>false</WholeProgramOptimization>
          <IntrinsicFunctions>true</IntrinsicFunctions>
          <GuardSignedReturns>true</GuardSignedReturns>
      </ClCompile>
      <Link>
          <AdditionalOptions>/BREPRO /DEBUGTYPE:CV,PDATA /DEPENDENTLOADFLAG:0x800 /FILEALIGN:0x1000 /NOOPTIDATA /BASERELOCCLUSTERING /NATVIS:$(MSBuildThisFileDirectory)\SystemInformer.natvis %(AdditionalOptions) $(ExternalLinkerOptions)</AdditionalOptions>
          <AdditionalDependencies>invalidcontinue.obj;noarg.obj;noenv.obj;nothrownew.obj;%(AdditionalDependencies)</AdditionalDependencies>
          <MinimumRequiredVersion>10</MinimumRequiredVersion>
          <TargetMachine>MachineARM64</TargetMachine>
          <FullProgramDatabaseFile>true</FullProgramDatabaseFile>
          <GenerateDebugInformation>true</GenerateDebugInformation>
          <UseUnicodeResponseFiles>true</UseUnicodeResponseFiles>
          <LinkTimeCodeGeneration>Default</LinkTimeCodeGeneration>
      </Link>
  </ItemDefinitionGroup>

  <!-- Release|Win32 Builds -->
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
      <ClCompile>
          <AdditionalOptions>/utf-8 $(SiMsvcNoDateOption) $(SiMsvcImportNoRegistryOption) $(SiMsvcTrimFileOption) %(AdditionalOptions) $(SiLlvmCompileOptions) $(ExternalAdditionalOptions)</AdditionalOptions>
          <PreprocessorDefinitions>WIN32;NDEBUG;_WINDOWS;_USRDLL;ENABLE_RESTRICTED;CONST_VTABLE;%(PreprocessorDefinitions);$(ExternalPreprocessorOptions)</PreprocessorDefinitions>
          <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
          <Optimization>MaxSpeed</Optimization>
          <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
          <CallingConvention>StdCall</CallingConvention>
          <FloatingPointModel>Precise</FloatingPointModel>
          <FunctionLevelLinking>true</FunctionLevelLinking>
          <IntrinsicFunctions>true</IntrinsicFunctions>
          <SpectreMitigation Condition="'$(SI_UNSAFE_BUILD)'=='true'">false</SpectreMitigation>
          <SpectreMitigation Condition="'$(SI_UNSAFE_BUILD)'!='true'">Spectre</SpectreMitigation>
          <IntelJCCErratum>true</IntelJCCErratum>
          <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
          <WholeProgramOptimization Condition="'$(SiLlvmBuild)' == 'true' and '$(SiLlvmLto)' != 'true'">false</WholeProgramOptimization>
          <WholeProgramOptimization Condition="'$(SiLlvmBuild)' != 'true' or '$(SiLlvmLto)' == 'true'">true</WholeProgramOptimization>
          <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
          <ControlFlowGuard>Guard</ControlFlowGuard>
      </ClCompile>
      <Link>
          <AdditionalOptions>/BREPRO /DEBUGTYPE:CV,PDATA /DEPENDENTLOADFLAG:0x800 /PDBALTPATH:%_PDB% /FILEALIGN:0x1000 $(SiMsvcPrivateLinkOptions) %(AdditionalOptions) $(ExternalLinkerOptions)</AdditionalOptions>
          <AdditionalDependencies>invalidcontinue.obj;noarg.obj;noenv.obj;nothrownew.obj;%(AdditionalDependencies)</AdditionalDependencies>
          <CETCompat>true</CETCompat>
          <MinimumRequiredVersion>6.01</MinimumRequiredVersion>
          <TargetMachine>MachineX86</TargetMachine>
          <GenerateDebugInformation>true</GenerateDebugInformation>
          <SetChecksum>true</SetChecksum>
          <OptimizeReferences>true</OptimizeReferences>
          <EnableCOMDATFolding>true</EnableCOMDATFolding>
          <UseUnicodeResponseFiles>true</UseUnicodeResponseFiles>
          <LinkTimeCodeGeneration Condition="'$(SiLlvmBuild)' != 'true' or '$(SiLlvmLto)' == 'true'">UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>
      </Link>
  </ItemDefinitionGroup>

  <!-- Release|x64 Builds -->
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
      <ClCompile>
          <AdditionalOptions>/utf-8 $(SiMsvcNoDateOption) $(SiMsvcImportNoRegistryOption) $(SiMsvcGuardXfgCompileOption) $(SiMsvcJumpTableOption) $(SiMsvcTrimFileOption) %(AdditionalOptions) $(SiLlvmCompileOptions) $(ExternalAdditionalOptions)</AdditionalOptions>
          <PreprocessorDefinitions>WIN64;NDEBUG;_WINDOWS;_USRDLL;ENABLE_RESTRICTED;CONST_VTABLE;%(PreprocessorDefinitions);$(ExternalPreprocessorOptions)</PreprocessorDefinitions>
          <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
          <EnableEnhancedInstructionSet>$(ExternalSimdOptions)</EnableEnhancedInstructionSet>
          <Optimization>MaxSpeed</Optimization>
          <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
          <CallingConvention>StdCall</CallingConvention>
          <FloatingPointModel>Precise</FloatingPointModel>
          <FunctionLevelLinking>true</FunctionLevelLinking>
          <IntrinsicFunctions>true</IntrinsicFunctions>
          <SpectreMitigation Condition="'$(SI_UNSAFE_BUILD)'=='true'">false</SpectreMitigation>
          <SpectreMitigation Condition="'$(SI_UNSAFE_BUILD)'!='true'">Spectre</SpectreMitigation>
          <IntelJCCErratum>true</IntelJCCErratum>
          <GuardEHContMetadata>true</GuardEHContMetadata>
          <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
          <WholeProgramOptimization Condition="'$(SiLlvmBuild)' == 'true' and '$(SiLlvmLto)' != 'true'">false</WholeProgramOptimization>
          <WholeProgramOptimization Condition="'$(SiLlvmBuild)' != 'true' or '$(SiLlvmLto)' == 'true'">true</WholeProgramOptimization>
          <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
          <ControlFlowGuard>Guard</ControlFlowGuard>
      </ClCompile>
      <Link>
          <AdditionalOptions>/BREPRO /DEBUGTYPE:CV,PDATA /DEPENDENTLOADFLAG:0x800 /PDBALTPATH:%_PDB% /FILEALIGN:0x1000 $(SiMsvcLtcgLinkOption) $(SiMsvcGuardXfgLinkOption) $(SiMsvcPrivateLinkOptions) %(AdditionalOptions) $(ExternalLinkerOptions)</AdditionalOptions>
          <AdditionalDependencies>invalidcontinue.obj;noarg.obj;noenv.obj;nothrownew.obj;%(AdditionalDependencies)</AdditionalDependencies>
          <CETCompat>true</CETCompat>
          <MinimumRequiredVersion>6.01</MinimumRequiredVersion>
          <TargetMachine>MachineX64</TargetMachine>
          <GenerateDebugInformation>true</GenerateDebugInformation>
          <SetChecksum>true</SetChecksum>
          <OptimizeReferences>true</OptimizeReferences>
          <EnableCOMDATFolding>true</EnableCOMDATFolding>
          <UseUnicodeResponseFiles>true</UseUnicodeResponseFiles>
          <LinkTimeCodeGeneration Condition="'$(SiLlvmBuild)' != 'true' or '$(SiLlvmLto)' == 'true'">UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>
      </Link>
  </ItemDefinitionGroup>

  <!-- Release|ARM64 Builds -->
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
      <ClCompile>
          <AdditionalOptions>/utf-8 $(SiMsvcNoDateOption) $(SiMsvcImportNoRegistryOption) $(SiMsvcTrimFileOption) %(AdditionalOptions) $(SiLlvmCompileOptions) $(ExternalAdditionalOptions)</AdditionalOptions>
          <PreprocessorDefinitions>WIN64;NDEBUG;_WINDOWS;_USRDLL;ENABLE_RESTRICTED;CONST_VTABLE;%(PreprocessorDefinitions);$(ExternalPreprocessorOptions)</PreprocessorDefinitions>
          <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
          <EnableEnhancedInstructionSet>$(ExternalSimdOptions)</EnableEnhancedInstructionSet>
          <Optimization>MaxSpeed</Optimization>
          <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
          <CallingConvention>StdCall</CallingConvention>
          <FloatingPointModel>Precise</FloatingPointModel>
          <FunctionLevelLinking>true</FunctionLevelLinking>
          <IntrinsicFunctions>true</IntrinsicFunctions>
          <GuardSignedReturns>true</GuardSignedReturns>
          <GuardEHContMetadata>true</GuardEHContMetadata>
          <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
          <WholeProgramOptimization Condition="'$(SiLlvmBuild)' == 'true' and '$(SiLlvmLto)' != 'true'">false</WholeProgramOptimization>
          <WholeProgramOptimization Condition="'$(SiLlvmBuild)' != 'true' or '$(SiLlvmLto)' == 'true'">true</WholeProgramOptimization>
          <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
          <ControlFlowGuard>Guard</ControlFlowGuard>
      </ClCompile>
      <Link>
          <AdditionalOptions>/BREPRO /DEBUGTYPE:CV,PDATA /DEPENDENTLOADFLAG:0x800 /PDBALTPATH:%_PDB% /FILEALIGN:0x1000 $(SiMsvcLtcgLinkOption) $(SiMsvcPrivateLinkOptions) %(AdditionalOptions) $(ExternalLinkerOptions)</AdditionalOptions>
          <AdditionalDependencies>invalidcontinue.obj;noarg.obj;noenv.obj;nothrownew.obj;%(AdditionalDependencies)</AdditionalDependencies>
          <MinimumRequiredVersion>10</MinimumRequiredVersion>
          <TargetMachine>MachineARM64</TargetMachine>
          <GenerateDebugInformation>true</GenerateDebugInformation>
          <SetChecksum>true</SetChecksum>
          <OptimizeReferences>true</OptimizeReferences>
          <EnableCOMDATFolding>true</EnableCOMDATFolding>
          <UseUnicodeResponseFiles>true</UseUnicodeResponseFiles>
          <LinkTimeCodeGeneration Condition="'$(SiLlvmBuild)' != 'true' or '$(SiLlvmLto)' == 'true'">UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>
      </Link>
  </ItemDefinitionGroup>

</Project>
